# You can change this to a newer version of MySQL available at
# https://hub.docker.com/_/mysql

# If you change the version here, you may also want change it in:
# `backups/install-mysqldump.sh`

FROM mysql:8.0.29
